In [18]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Fix 'x3' to be a flat list instead of a list inside a list
data = {
    'y': [78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4],
    'x1': [7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10],
    'x2': [26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68],
    'x3': [6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8],
    'x4': [60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12]
}

# Convert the dictionary to a pandas DataFrame
df = pd.DataFrame(data)
df



y  x1  x2  x3  x4
0    78.5   7  26   6  60
1    74.3   1  29  15  52
2   104.3  11  56   8  20
3    87.6  11  31   8  47
4    95.9   7  52   6  33
5   109.2  11  55   9  22
6   102.7   3  71  17   6
7    72.5   1  31  22  44
8    93.1   2  54  18  22
9   115.9  21  47   4  26
10   83.8   1  40  23  34
11  113.3  11  66   9  12
12  109.4  10  68   8  12

In [20]:
# Separar la variable (y) y las variables (x1, x2, x3, x4)
X = df[['x1', 'x2', 'x3', 'x4']].values
y = df['y'].values
ones=np.ones((X.shape[0],1)) # Changed 'xshape' to 'X.shape'
x=np.hstack((ones,X)) # se agrega el 1
print(x)
print(y)

[[ 1.  7. 26.  6. 60.]
 [ 1.  1. 29. 15. 52.]
 [ 1. 11. 56.  8. 20.]
 [ 1. 11. 31.  8. 47.]
 [ 1.  7. 52.  6. 33.]
 [ 1. 11. 55.  9. 22.]
 [ 1.  3. 71. 17.  6.]
 [ 1.  1. 31. 22. 44.]
 [ 1.  2. 54. 18. 22.]
 [ 1. 21. 47.  4. 26.]
 [ 1.  1. 40. 23. 34.]
 [ 1. 11. 66.  9. 12.]
 [ 1. 10. 68.  8. 12.]]
[ 78.5  74.3 104.3  87.6  95.9 109.2 102.7  72.5  93.1 115.9  83.8 113.3
 109.4]


In [21]:
#se transpone (despejar)
xtras=x.T
print(xtras)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 7.  1. 11. 11.  7. 11.  3.  1.  2. 21.  1. 11. 10.]
 [26. 29. 56. 31. 52. 55. 71. 31. 54. 47. 40. 66. 68.]
 [ 6. 15.  8.  8.  6.  9. 17. 22. 18.  4. 23.  9.  8.]
 [60. 52. 20. 47. 33. 22.  6. 44. 22. 26. 34. 12. 12.]]


In [23]:
#multiplicacion entre las matrices (fila por columna)
Xtx=np.dot(xtras,x) # En este caso y para darle la "forma como si fuera cuadratica se multiplica por la trasnpuesta"
print(Xtx)

[[1.3000e+01 9.7000e+01 6.2600e+02 1.5300e+02 3.9000e+02]
 [9.7000e+01 1.1390e+03 4.9220e+03 7.6900e+02 2.6200e+03]
 [6.2600e+02 4.9220e+03 3.3050e+04 7.2010e+03 1.5739e+04]
 [1.5300e+02 7.6900e+02 7.2010e+03 2.2930e+03 4.6280e+03]
 [3.9000e+02 2.6200e+03 1.5739e+04 4.6280e+03 1.5062e+04]]


In [29]:
xtxpinv = np.linalg.pinv(Xtx)  # Se calcula la pseudoinversa (esto es lo que nos ayuda a calcular la matriz cuando no es cuadrada)
print(xtxpinv)  # Se imprime el resultado


[[ 8.20654575e+02 -8.44180186e+00 -8.45777985e+00 -8.63453878e+00
  -8.28974378e+00]
 [-8.44180186e+00  9.27104019e-02  8.56862094e-02  9.26373566e-02
   8.44549553e-02]
 [-8.45777985e+00  8.56862094e-02  8.75602572e-02  8.78666397e-02
   8.55980995e-02]
 [-8.63453878e+00  9.26373566e-02  8.78666397e-02  9.52014098e-02
   8.63919189e-02]
 [-8.28974378e+00  8.44549553e-02  8.55980995e-02  8.63919189e-02
   8.40311912e-02]]


In [30]:
b=xtxpinv.dot(xtras).dot(y)
print(b)

[62.40536931  1.55110265  0.51016758  0.1019094  -0.14406103]


In [31]:


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create the linear regression model
model = LinearRegression()

# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')
print(f'Coefficients: {model.coef_}')
print(f'Intercept: {model.intercept_}')


Mean Squared Error: 2.394623995709894
Coefficients: [ 1.2025628   0.28487458 -0.17808246 -0.3639949 ]
Intercept: 85.44669988722089
